### ISSUE TITLE
Unable to get get database to install during app inhiation. 

### ISSUE THREAD

**Issue by smarthomeaf** [ep1cman/unifi-protect-backup#116]
* Unifi Protect Backup version: 1.1.2
* Unifi Protect version: Protect 2.8.35
* Python version: 3.11.6
* Operating System: TRUENA Scale
* Are you using a docker container or native?:
Truenas APP (docker)

### Description

App starts in truenas, but it looks like the database fails to create
### What I Did

```
2023-11-10T15:16:21.105683748-05:00 [migrations] started
2023-11-10T15:16:21.105808750-05:00 [migrations] no migrations found
2023-11-10T15:16:21.138439302-05:00 cp: cannot stat '/root/.config/rclone/rclone.conf': No such file or directory
2023-11-10T15:16:22.511357246-05:00 ───────────────────────────────────────
2023-11-10T15:16:22.511508622-05:00   _____ __ __ _____ _____ _____ _____ 
2023-11-10T15:16:22.511595695-05:00  |     |  |  |   __|_   _|     |     |
2023-11-10T15:16:22.511631315-05:00  |   --|  |  |__   | | | |  |  | | | |
2023-11-10T15:16:22.511663886-05:00  |_____|_____|_____| |_| |_____|_|_|_|
2023-11-10T15:16:22.511694877-05:00        _____ __ __ _ __    ____  
2023-11-10T15:16:22.511782630-05:00       | __  |  |  | |  |  |    \ 
2023-11-10T15:16:22.511820225-05:00       | __ -|  |  | |  |__|  |  |
2023-11-10T15:16:22.511852239-05:00       |_____|_____|_|_____|____/ 
2023-11-10T15:16:22.511901813-05:00 
2023-11-10T15:16:22.511935087-05:00   Based on images from linuxserver.io
2023-11-10T15:16:22.511967618-05:00 ───────────────────────────────────────
2023-11-10T15:16:22.512823488-05:00 
2023-11-10T15:16:22.512957012-05:00 To support LSIO projects visit:
2023-11-10T15:16:22.513000451-05:00 https://www.linuxserver.io/donate/
2023-11-10T15:16:22.513077501-05:00 
2023-11-10T15:16:22.513111127-05:00 ───────────────────────────────────────
2023-11-10T15:16:22.513143554-05:00 GID/UID
2023-11-10T15:16:22.513175746-05:00 ───────────────────────────────────────
2023-11-10T15:16:22.528218426-05:00 
2023-11-10T15:16:22.528344282-05:00 User UID:    568
2023-11-10T15:16:22.528422276-05:00 User GID:    568
2023-11-10T15:16:22.528457565-05:00 ───────────────────────────────────────
2023-11-10T15:16:22.528488120-05:00 
2023-11-10T15:16:22.699026742-05:00 [custom-init] No custom files found, skipping...
2023-11-10T15:16:22.748739853-05:00 [ls.io-init] done.
2023-11-10T15:16:22.767048489-05:00 v
2023-11-10T15:16:24.242955448-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :  Config:
2023-11-10T15:16:24.243081343-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    address='xxx.xxx.xxx.xxx.xxx'
2023-11-10T15:16:24.243148745-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    port=443
2023-11-10T15:16:24.243304581-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    username='xxx'
2023-11-10T15:16:24.243522585-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    password=REDACTED
2023-11-10T15:16:24.243579226-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    verify_ssl=False
2023-11-10T15:16:24.243645315-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    rclone_destination='local:/'
2023-11-10T15:16:24.243878220-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    retention=relativedelta(days=+7)
2023-11-10T15:16:24.244015510-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    rclone_args=''
2023-11-10T15:16:24.244147463-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    rclone_purge_args=''
2023-11-10T15:16:24.244338634-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    ignore_cameras=()
2023-11-10T15:16:24.244560322-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    verbose=1
2023-11-10T15:16:24.244616805-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    detection_types=['motion', 'person', 'vehicle', 'ring']
2023-11-10T15:16:24.244673425-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    file_structure_format='{camera_name}/{event.start:%Y-%m-%d}/{event.end:%Y-%m-%dT%H-%M-%S} {detection_type}.mp4'
2023-11-10T15:16:24.244780036-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    sqlite_path='/config/database/events.sqlite'
2023-11-10T15:16:24.244904570-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    download_buffer_size=512.0MiB
2023-11-10T15:16:24.245039110-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    purge_interval=relativedelta(days=+1)
2023-11-10T15:16:24.245173226-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    apprise_notifiers=()
2023-11-10T15:16:24.245293067-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    skip_missing=False
2023-11-10T15:16:24.245433962-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    download_rate_limit=None events per minute
2023-11-10T15:16:24.245590723-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    max_event_length=7200s
2023-11-10T15:16:24.247117474-05:00 2023-11-10 15:16:24 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Starting...
2023-11-10T15:16:24.247250377-05:00 2023-11-10 15:16:24 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Checking rclone configuration...
2023-11-10T15:16:24.247553369-05:00 2023-11-10 15:16:24 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :  rclone found: /usr/bin/rclone
2023-11-10T15:16:24.655104383-05:00 2023-11-10 15:16:24 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Connecting to Unifi Protect...
2023-11-10T15:16:25.783608609-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Found cameras:
2023-11-10T15:16:25.784036708-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 64eab48d0250ab03e401174d: G5 Pro
2023-11-10T15:16:25.784291317-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 5e3f200d0134f503e70003ee: Back Door
2023-11-10T15:16:25.784638240-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 5f55c94802e36903e70078fc: Garage
2023-11-10T15:16:25.785007217-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 64ea659d02d5ab03e401134d: Front Door Bell
2023-11-10T15:16:25.785342971-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 5e3f200d011bf503e70003ed: Side Door
2023-11-10T15:16:25.785734711-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 5f55bfca017e6903e70078c8: test
2023-11-10T15:16:25.786077824-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :   - 649f78e00258aa03e4001ecd: New Basement
2023-11-10T15:16:25.786498419-05:00 2023-11-10 15:16:25 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :  NVR TZ: America/New_York
2023-11-10T15:16:25.786846250-05:00 2023-11-10 15:16:25 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :  Local TZ: EST
2023-11-10T15:16:25.787284270-05:00 2023-11-10 15:16:25 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Database doesn't exist, creating a new one
2023-11-10T15:16:25.792657830-05:00 2023-11-10 15:16:25 [   ERROR   ] unifi_protect_backup.unifi_protect_backup_core :  Unexpected exception occurred in main loop:
2023-11-10T15:16:25.792774692-05:00 Traceback (most recent call last):
2023-11-10T15:16:25.792812360-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 216, in start
2023-11-10T15:16:25.792897544-05:00     self._db = await create_database(self._sqlite_path)
2023-11-10T15:16:25.792934119-05:00                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:25.792968171-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 31, in create_database
2023-11-10T15:16:25.793001838-05:00     db = await aiosqlite.connect(path)
2023-11-10T15:16:25.793036175-05:00          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:25.793092057-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 137, in _connect
2023-11-10T15:16:25.793126660-05:00     self._connection = await future
2023-11-10T15:16:25.793159367-05:00                        ^^^^^^^^^^^^
2023-11-10T15:16:25.793193307-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 102, in run
2023-11-10T15:16:25.793226679-05:00     result = function()
2023-11-10T15:16:25.793279261-05:00              ^^^^^^^^^^
2023-11-10T15:16:25.793313756-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 397, in connector
2023-11-10T15:16:25.793349481-05:00     return sqlite3.connect(loc, **kwargs)
2023-11-10T15:16:25.793383541-05:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:25.793417608-05:00 sqlite3.OperationalError: unable to open database file
2023-11-10T15:16:35.797904810-05:00 2023-11-10 15:16:35 [   ERROR   ] aiorun                                     :  Unhandled exception; stopping loop: 'Task exception was never retrieved'
2023-11-10T15:16:35.798115376-05:00 Traceback (most recent call last):
2023-11-10T15:16:35.798159836-05:00   File "/usr/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
2023-11-10T15:16:35.798199141-05:00     await coro
2023-11-10T15:16:35.798233842-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 216, in start
2023-11-10T15:16:35.798292854-05:00     self._db = await create_database(self._sqlite_path)
2023-11-10T15:16:35.798328097-05:00                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.798362000-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 31, in create_database
2023-11-10T15:16:35.798394481-05:00     db = await aiosqlite.connect(path)
2023-11-10T15:16:35.798446821-05:00          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.798480508-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 137, in _connect
2023-11-10T15:16:35.798512791-05:00     self._connection = await future
2023-11-10T15:16:35.798544646-05:00                        ^^^^^^^^^^^^
2023-11-10T15:16:35.798577592-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 102, in run
2023-11-10T15:16:35.798628667-05:00     result = function()
2023-11-10T15:16:35.798662182-05:00              ^^^^^^^^^^
2023-11-10T15:16:35.798694738-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 397, in connector
2023-11-10T15:16:35.798727482-05:00     return sqlite3.connect(loc, **kwargs)
2023-11-10T15:16:35.798760792-05:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.798794487-05:00 sqlite3.OperationalError: unable to open database file
2023-11-10T15:16:35.804687509-05:00 Traceback (most recent call last):
2023-11-10T15:16:35.804796635-05:00   File "/usr/bin/unifi-protect-backup", line 8, in <module>
2023-11-10T15:16:35.804999962-05:00     sys.exit(main())
2023-11-10T15:16:35.805111029-05:00              ^^^^^^
2023-11-10T15:16:35.805163608-05:00   File "/usr/lib/python3.11/site-packages/click/core.py", line 1137, in __call__
2023-11-10T15:16:35.807376779-05:00     return self.main(*args, **kwargs)
2023-11-10T15:16:35.807535163-05:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.807573932-05:00   File "/usr/lib/python3.11/site-packages/click/core.py", line 1062, in main
2023-11-10T15:16:35.809099239-05:00     rv = self.invoke(ctx)
2023-11-10T15:16:35.809203753-05:00          ^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.809245187-05:00   File "/usr/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
2023-11-10T15:16:35.811043568-05:00     return ctx.invoke(self.callback, **ctx.params)
2023-11-10T15:16:35.811147744-05:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.811184401-05:00   File "/usr/lib/python3.11/site-packages/click/core.py", line 763, in invoke
2023-11-10T15:16:35.812409798-05:00     return __callback(*args, **kwargs)
2023-11-10T15:16:35.812518779-05:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.812559498-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/cli.py", line 217, in main
2023-11-10T15:16:35.813074051-05:00     run(event_listener.start(), stop_on_unhandled_errors=True)
2023-11-10T15:16:35.813204432-05:00   File "/usr/lib/python3.11/site-packages/aiorun.py", line 371, in run
2023-11-10T15:16:35.813811761-05:00     raise pending_exception_to_raise
2023-11-10T15:16:35.813903401-05:00   File "/usr/lib/python3.11/site-packages/aiorun.py", line 219, in new_coro
2023-11-10T15:16:35.814276497-05:00     await coro
2023-11-10T15:16:35.814387163-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 216, in start
2023-11-10T15:16:35.814929046-05:00     self._db = await create_database(self._sqlite_path)
2023-11-10T15:16:35.814986444-05:00                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.815025901-05:00   File "/usr/lib/python3.11/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 31, in create_database
2023-11-10T15:16:35.815471653-05:00     db = await aiosqlite.connect(path)
2023-11-10T15:16:35.815566875-05:00          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.815606129-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 137, in _connect
2023-11-10T15:16:35.816012453-05:00     self._connection = await future
2023-11-10T15:16:35.816099108-05:00                        ^^^^^^^^^^^^
2023-11-10T15:16:35.816208225-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 102, in run
2023-11-10T15:16:35.816542195-05:00     result = function()
2023-11-10T15:16:35.816634730-05:00              ^^^^^^^^^^
2023-11-10T15:16:35.816671117-05:00   File "/usr/lib/python3.11/site-packages/aiosqlite/core.py", line 397, in connector
2023-11-10T15:16:35.817439911-05:00     return sqlite3.connect(loc, **kwargs)
2023-11-10T15:16:35.817591325-05:00            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-11-10T15:16:35.817629119-05:00 sqlite3.OperationalError: unable to open database file
2023-11-10T15:16:37.188269058-05:00 v

**Comment by smarthomeaf** [comment]
This can be closed.  After some additional  debugging, i uncovered that it was an acl issue.
