### ISSUE TITLE
0.10.4 can't connect to Unifi Protect

### ISSUE THREAD

**Issue by mmolitor87** [ep1cman/unifi-protect-backup#130]
* Unifi Protect Backup version: 0.10.4
* Unifi Protect version: 2.11.21
* Python version: 3.10
* Operating System: Ubuntu 22.04.4 LTS
* Are you using a docker container or native?: Native

### Description
After upgrading it can't connect to Protect.

### What I Did

```
2024-02-17 13:56:16 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 2s...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 190, in start
    await self._protect.update()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 673, in update
    self._bootstrap = await self.get_bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 991, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 379, in api_request_obj
    data = await self.api_request(
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 358, in api_request
    data = await self.api_request_raw(
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 319, in api_request_raw
    response = await self.request(
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 255, in request
    await self.ensure_authenticated()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 416, in ensure_authenticated
    await self.authenticate()
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 441, in authenticate
    response = await self.request("post", url=url, json=auth)
  File "/usr/local/lib/python3.10/dist-packages/pyunifiprotect/api.py", line 257, in request
    request_url = self._url.joinpath(url[1:])
AttributeError: 'URL' object has no attribute 'joinpath'
```

Reverted back to 0.9.5 and have no issues. Let me know if you need any other information.

**Comment by ep1cman** [comment]
Hi,

Thanks for reporting this, looks like its an issue with the underlying python library this tool is based on. I will raise an issue with them and report back once its resolved

**Comment by ep1cman** [comment]
should be fixed in the latest release
