### ISSUE TITLE
Assert video is not None

### ISSUE THREAD

**Issue by andrewglass3** [ep1cman/unifi-protect-backup#143]
* Unifi Protect Backup version: latest
* Unifi Protect version: 3.0.26
* Python version: 3.11.8
* Operating System: linux - ubuntu 22.04 headless running Docker version 26.1.0, build 9714adc
* Are you using a docker container or native?: Docker

### Description

The container is running and backing up however its only backing up one of 3 cameras.

Im seeing the following logs in docker:

`2024-05-02 09:29:59 [   INFO    ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Downloading event: 6633463001ab0203e400042b
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Remaining Download Queue: 0
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Video Download Buffer: 0.0B/512.0MiB
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Camera: Front bedroom
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Type: motion
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Start: 2024-05-02T08-52-09 (1714636329.798)
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    End: 2024-05-02T08-52-27 (1714636347.149)
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Duration: 17.351s
2024-05-02 09:29:59 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Downloading video...
2024-05-02 09:29:59 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 1, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:30:00 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 2, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:30:01 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 3, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:30:02 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 4, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:30:03 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 5, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:30:04 [   ERROR   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Download failed after 5 attempts, abandoning event 6633463001ab0203e400042b:
2024-05-02 09:30:04 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Event failed download attempt 9
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 145, in start
    assert video is not None
           ^^^^^^^^^^^^^^^^^
AssertionError`

### What I Did
Ive tried restarting the docker container, Ive also double checked the role and user I created un Unifi.

One step of the instructions I could not see in the UDM SE web ui was the step:

- Select the newly created user in the list, and navigate to the Assignments tab in the left-hand pane, and ensure all cameras are ticked.

Could I have missed something here that is causing the issue?

```
Paste the command(s) you ran and the output.

docker logs f23ede089ab0

If there was a crash, please include the traceback here.

`2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.missing_event_checker :  Running check for missing events...
2024-05-02 09:34:54 [  WARNING  ] unifi_protect_backup.missing_event_checker :   Found missing events, adding to backup queue
2024-05-02 09:34:54 [   INFO    ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Downloading event: 6633463001ab0203e400042b
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Remaining Download Queue: 0
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Video Download Buffer: 0.0B/512.0MiB
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Camera: Front bedroom
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Type: motion
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Start: 2024-05-02T08-52-09 (1714636329.798)
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    End: 2024-05-02T08-52-27 (1714636347.149)
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Duration: 17.351s
2024-05-02 09:34:54 [   DEBUG   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]    Downloading video...
2024-05-02 09:34:54 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 1, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:34:55 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 2, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:34:56 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 3, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:34:57 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 4, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:34:58 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]      Failed download attempt 5, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 185, in _download
    assert isinstance(video, bytes)
AssertionError
2024-05-02 09:34:59 [   ERROR   ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Download failed after 5 attempts, abandoning event 6633463001ab0203e400042b:
2024-05-02 09:34:59 [  WARNING  ] unifi_protect_backup.downloader            : [6633463001ab0203e400042b]  Event failed download attempt 10
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/unifi_protect_backup/downloader.py", line 145, in start
    assert video is not None
           ^^^^^^^^^^^^^^^^^
AssertionError`
```
Thank you for your help and time figuring this out.

Kind regards
Andrew

**Comment by andrewglass3** [comment]
I think this may have had something to do with the image version I was setting. In my docker-compose I was setting

`image: ghcr.io/ep1cman/unifi-protect-backup:latest`

changing it to the following seems to have stopped these errors from showing:

`image: ghcr.io/ep1cman/unifi-protect-backup:0.10.7`

Its now also picking up all my cameras correctly - apologies for the noise.

Ill close this issue now.

Kind regards

Andrew

**Comment by ep1cman** [comment]
This would not have been caused by the container version. It's caused by UniFi protect serving an empty file which happens every so often. I think UniFi protect sometimes fails to save clips

**Comment by andrewglass3** [comment]
Ah excellent :) Thank you for letting me know - I wasn't sure as it was the first time I have tried your app. Cool app by the way, thank you for developing it :)
