### ISSUE TITLE
Local backup scenario - error "rclone does not have a remote called `local`"

### ISSUE THREAD

**Issue by WiggyToo** [ep1cman/unifi-protect-backup#157]
* Unifi Protect Backup version: 0.11.0
* Unifi Protect version: 4.0.33
* Python version: 3.12.3
* Operating System: Debian
* Are you using a docker container or native?: docker container on OMV

### Description

Describe what you were trying to get done.
I am trying to test my installation for local backup

Tell us what happened, what went wrong, and what you expected to happen.
I have installed the docker container and am executing the command unifi-protect-backup in the container

### What I Did
Paste the command(s) you ran and the output.
If there was a crash, please include the traceback here.
```
unifi-protect-backup
2024-07-16 16:08:00 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Starting...
2024-07-16 16:08:00 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Checking rclone configuration...
2024-07-16 16:08:00 [   ERROR   ] unifi_protect_backup.unifi_protect_backup_core :  Unexpected exception occurred in main loop:
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 189, in start
    await self._check_rclone()
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 331, in _check_rclone
    raise ValueError(f"rclone does not have a remote called `{remote}`")
ValueError: rclone does not have a remote called `local`
2024-07-16 16:08:10 [   ERROR   ] aiorun                                     :  Unhandled exception; stopping loop: 'Task exception was never retrieved'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 189, in start
    await self._check_rclone()
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 331, in _check_rclone
    raise ValueError(f"rclone does not have a remote called `{remote}`")
ValueError: rclone does not have a remote called `local`
Traceback (most recent call last):
  File "/usr/bin/unifi-protect-backup", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/cli.py", line 232, in main
    run(event_listener.start(), stop_on_unhandled_errors=True)
  File "/usr/lib/python3.12/site-packages/aiorun.py", line 371, in run
    raise pending_exception_to_raise
  File "/usr/lib/python3.12/site-packages/aiorun.py", line 219, in new_coro
    await coro
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 189, in start
    await self._check_rclone()
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 331, in _check_rclone
    raise ValueError(f"rclone does not have a remote called `{remote}`")
ValueError: rclone does not have a remote called `local`
root@37ed9413f65f:/app#
```

My docker container file is as follows:

name: protectbackup
services:
    unifi-protect-backup:
        environment:
            - UFP_USERNAME=[my user]
            - UFP_PASSWORD=[my password]
            - UFP_ADDRESS=[my ip]
            - UFP_SSL_VERIFY=false
        volumes:
            - /srv/dev-disk-by-uuid-640a68fa-18cd-a44f-9eda-f6ce16356599/Backup/Protect:/data
            - /srv/dev-disk-by-uuid-640a68fa-18cd-a44f-9eda-f6ce16356599/Backup/Protect:/config/database/
        image: ghcr.io/ep1cman/unifi-protect-backup

Thanks in advance for any help,
Gav

**Comment by ep1cman** [comment]
Looks like you haven't passed an rclone config file to the container

**Comment by WiggyToo** [comment]
That's right, I used this example:

Quote:
Backing up locally:
By default, if no rclone config is provided clips will be backed up to /data.

```
docker run \
  -e UFP_USERNAME='USERNAME' \
  -e UFP_PASSWORD='PASSWORD' \
  -e UFP_ADDRESS='UNIFI_PROTECT_IP' \
  -e UFP_SSL_VERIFY='false' \
  -v '/path/to/save/clips':'/data' \
  -v '/path/to/save/database':/config/database/ \
  ghcr.io/ep1cman/unifi-protect-backup
```

Have I misunderstood?
Gav

**Comment by WiggyToo** [comment]
I switched to a remote back up on OneDrive, and after some debugging and the like the log suggests it is now working and files are appearing in OneDrive - so looking good.

I had a problem with the service logging in to Protect due to some rate limiting (this showed up when I tested the login by logging into the local device with the backup user) - this fix worked for me, 

https://community.ui.com/questions/Unifi-Controller-Login-Rate-Limit-Youve-reached-the-login-attempt-limit-Please-wait-a-few-minutes-b/15ae306b-6eb3-46bd-8a56-629ae39b4e48#answer/960ad474-0ed6-4ad8-ad2b-39048b4c3631

Otherwise the problems I had were all resolved by reading hte documents properly and trial and error.

Many thanks for producing this work.

Regards,
Gav

**Comment by WiggyToo** [comment]
Closed
