### ISSUE TITLE
 Failed download

### ISSUE THREAD

**Issue by idscomm** [ep1cman/unifi-protect-backup#158]
* Unifi Protect Backup version: Latest
* Unifi Protect version: 4.0.33
* Python version: From Latest Docker (ghcr.io/ep1cman/unifi-protect-backup:latest)
* Operating System: Unraid Docker
* Are you using a docker container or native?: Docker

### Description

Looking at the videos, I noticed that some event were missing from my OneDrive.

### What I Did

I restarted the container and looked at the log. I once in a while see this error:

2024-07-16 22:06:08 [  WARNING  ] unifi_protect_backup.downloader            : [668eb1ba037e5b03e400c089]      Failed download attempt 4, retying in 1s
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/downloader.py", line 184, in _download
    video = await self._protect.get_camera_video(event.camera_id, event.start, event.end)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1411, in get_camera_video
    return await self.export_camera_video(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 1333, in export_camera_video
    return await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 239, in api_request_raw
    response = await self._os.request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 378, in request
    response = await req_context.__aenter__()  # noqa: PLC2801
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/aiohttp/client.py", line 608, in _request
    await resp.start(conn)
  File "/usr/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 971, in start
    with self._timer:
  File "/usr/lib/python3.12/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

I have no clue what this means, any help would be appreciated.

Thank you!

**Comment by nkiest** [comment]
I’m having the exact same problem, same errors.

**Comment by ep1cman** [comment]
Try using the new experimental download option and see if that helps

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
