### ISSUE TITLE
Issue authenticating against Unifi OS 4.x

### ISSUE THREAD

**Issue by LloydPickering** [ep1cman/unifi-protect-backup#161]
* Unifi Protect Backup version: 0.11.0 (latest and dev)
* Unifi Protect version: v4.0.33
* Unifi OS v4.0.6 on a Dream Machine Pro
* Python version: Whatever ships in the docker container
* Operating System: UnRaid (but with Docker)
* Are you using a docker container or native?: Docker

### Description

Initial setup. Can't connect to Unifi Protect. Appears to be related to 

### What I Did
docker run
  -d
  --name='UnifiProtectBackup'
  --net='host'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="XXXXXXXXXXXXXXX"
  -e HOST_CONTAINERNAME="UnifiProtectBackup"
  -e ' UFP_USERNAME'='XXXXXXXXXXXXXXX'
  -e 'UFP_PASSWORD'='XXXXXXXXXXXXXXX'
  -e 'UFP_ADDRESS'='XXXXXXXXXXXXXXX'
  -e 'UFP_SSL_VERIFY'='false'
  -e 'SKIP_MISSING'='true'
  -e 'EXPERIMENTAL_DOWNLOADER'='false'
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/appdata/UnifiBackup/':'/config/database':'rw'
  -v '/mnt/user/unifi_backup/':'/data':'rw' 
  'ghcr.io/ep1cman/unifi-protect-backup:latest'

This results in the following log:
AttributeError: 'NoneType' object has no attribute 'split'
2024-08-06 22:02:28 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 4s...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 196, in start
    await self._protect.update()
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 524, in update
    self._bootstrap = await self.get_bootstrap()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 842, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 295, in api_request_obj
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 274, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 239, in api_request_raw
    response = await self._os.request(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 361, in request
    await self.ensure_authenticated()
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 421, in ensure_authenticated
    await self.authenticate()
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 460, in authenticate
    response = await self.request("post", url=url, json=auth)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 380, in request
    await self._update_last_token_cookie(response, require=require_auth)
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 494, in _update_last_token_cookie
    for name, value in [c.split("=") for c in cookies.split(";") if "=" in c]:
                                              ^^^^^^^^^^^^^

If instead I use the same settings but with image:
ghcr.io/ep1cman/unifi-protect-backup:dev

I get logs:

2024-08-06 22:04:16 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 5s...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 190, in start
    await self._protect.update()
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 524, in update
    self._bootstrap = await self.get_bootstrap()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 842, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 295, in api_request_obj
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 274, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/api.py", line 249, in api_request_raw
    await self._os.verify_response(url, response)
  File "/usr/lib/python3.12/site-packages/pyunifiprotect/session.py", line 332, in verify_response
    raise NotAuthorized(msg % (url, response.status, reason))
pyunifiprotect.exceptions.NotAuthorized: Request failed: /proxy/protect/api/bootstrap - Status: 401 - Reason: {'code': 401, 'message': 'Unauthorized'}

Username and password are correct and the homeassistant unifi protect plugin works correctly and can access the cameras.

This appears to be related to #148 and #150 and is likely an issue in pyunifiprotect dependency. Homeassistant uses the forked UIProtect library which seems to be why Homeassistant can connect properly.

Created PR #160 as a potential solution, but as I'm not a Python dev, or doing any dev on Linux I'm a bit out of my depth getting it over the line.

**Comment by ep1cman** [comment]
I've pushed a built container based on the PR you provided to the dev tag. Please try that and let me know if it works

**Comment by LloydPickering** [comment]
@ep1cman I get the following logs in container which match what I was getting from local docker build (I thought I was just being silly in some way):

/package/admin/s6-overlay-3.1.6.2/etc/s6-rc/scripts/cont-init: line 20: /etc/cont-init.d/30-config: Permission denied
s6-supervise unifi-protect-backup: warning: unable to spawn ./run (waiting 60 seconds): Permission denied
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.

**Comment by ep1cman** [comment]
huh, yeah now that I actually try to run it, I get the same issue. This must be a change in the upstream base container image. I will figure it out and get a new build uploaded ASAP

**Comment by ep1cman** [comment]
Ok please try `:dev` now, you might face a error about too many requests for authenticating, if you do you will have to wait a while before running this tool again. Unifi seem to have implemented extremely agressive rate limiting on creating auth cookies

**Comment by LloydPickering** [comment]
Seem to be getting closer... I get 403s followed by 429 too many requests.

cp: cannot stat '/root/.config/rclone/rclone.conf': No such file or directory
[migrations] started
[migrations] no migrations found
usermod: no changes
───────────────────────────────────────
  _____ __ __ _____ _____ _____ _____ 
 |     |  |  |   __|_   _|     |     |
 |   --|  |  |__   | | | |  |  | | | |
 |_____|_____|_____| |_| |_____|_|_|_|
       _____ __ __ _ __    ____  
      | __  |  |  | |  |  |    \ 
      | __ -|  |  | |  |__|  |  |
      |_____|_____|_|_____|____/ 

  Based on images from linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    911
User GID:    911
───────────────────────────────────────
[custom-init] No custom files found, skipping...
[ls.io-init] done.
v
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :  Config:
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    address='XXXXXXXXX'
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    port=443
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    username='XXXXXXXXX'
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    password=REDACTED
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    verify_ssl=False
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    rclone_destination='local:/data'
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    retention=relativedelta(days=+7)
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    rclone_args=''
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    rclone_purge_args=''
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    ignore_cameras=()
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    verbose=1
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    detection_types=['motion', 'person', 'vehicle', 'ring']
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    file_structure_format='{camera_name}/{event.start:%Y-%m-%d}/{event.end:%Y-%m-%dT%H-%M-%S} {detection_type}.mp4'
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    sqlite_path='/config/database/events.sqlite'
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    download_buffer_size=512.0MiB
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    purge_interval=relativedelta(days=+1)
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    apprise_notifiers=()
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    skip_missing=True
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    download_rate_limit=None events per minute
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    max_event_length=7200s
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :    use_experimental_downloader=False
2024-08-07 21:16:05 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Starting...
2024-08-07 21:16:05 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Checking rclone configuration...
2024-08-07 21:16:05 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup_core :  rclone found: /usr/bin/rclone
2024-08-07 21:16:05 [   INFO    ] unifi_protect_backup.unifi_protect_backup_core :  Connecting to Unifi Protect...
2024-08-07 21:16:05 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 0s...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 196, in start
    await self._protect.update()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 820, in update
    bootstrap = await self.get_bootstrap()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 1170, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 472, in api_request_obj
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 446, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 388, in api_request_raw
    response = await self.request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 325, in request
    await self.ensure_authenticated()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 510, in ensure_authenticated
    await self.authenticate()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 535, in authenticate
    await self._raise_for_status(response, True)
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 425, in _raise_for_status
    raise NotAuthorized(msg % (url, status, reason))
uiprotect.exceptions.NotAuthorized: Request failed: https://XXXXXXXXX/api/auth/login - Status: 403 - Reason: Forbidden
2024-08-07 21:16:06 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 1s...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 196, in start
    await self._protect.update()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 820, in update
    bootstrap = await self.get_bootstrap()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 1170, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 472, in api_request_obj
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 446, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 388, in api_request_raw
    response = await self.request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 325, in request
    await self.ensure_authenticated()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 510, in ensure_authenticated
    await self.authenticate()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 535, in authenticate
    await self._raise_for_status(response, True)
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 425, in _raise_for_status
    raise NotAuthorized(msg % (url, status, reason))
uiprotect.exceptions.NotAuthorized: Request failed: https://XXXXXXXXX/api/auth/login - Status: 403 - Reason: Forbidden

Then eventually:

2024-08-07 21:16:36 [  WARNING  ] unifi_protect_backup.unifi_protect_backup_core :  Failed to connect to UniFi Protect, retrying in 8s...
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 196, in start
    await self._protect.update()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 820, in update
    bootstrap = await self.get_bootstrap()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 1170, in get_bootstrap
    data = await self.api_request_obj("bootstrap")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 472, in api_request_obj
    data = await self.api_request(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 446, in api_request
    data = await self.api_request_raw(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 388, in api_request_raw
    response = await self.request(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 325, in request
    await self.ensure_authenticated()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 510, in ensure_authenticated
    await self.authenticate()
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 535, in authenticate
    await self._raise_for_status(response, True)
  File "/usr/lib/python3.12/site-packages/uiprotect/api.py", line 428, in _raise_for_status
    raise NvrError(msg % (url, status, reason))
uiprotect.exceptions.NvrError: Request failed: https://XXXXXXXXX/api/auth/login - Status: 429 - Reason: Too Many Requests
2024-08-07 21:16:41 [  WARNING  ] aiorun                                     :  Stopping the loop

**Comment by ep1cman** [comment]
Yup this is the odd authentication rate limiting I spoke about. Uiprotect will cache the cookie once it's authenticated and reuse it, but if you ask for new ones too often this happens. I ended up having to map in the cookie file from my local copy of the tool into the container to get it to work. 

I will investigate more to try and understand how to stop it if you don't already have a cookie

**Comment by ep1cman** [comment]
Did this eventually resolve itself from you once the rate limiting cooled down?

**Comment by LloydPickering** [comment]
Sorry I haven't replied sooner, had a busy period over the weekend. I'm still getting 403 followed by 429 with the dev image. I don't know why I'm getting the 403 though, that's the bit that seems strange.

I suspect it might be the way I have access setup using tailscale to connect to the UDM. Reverse proxy might be causing issues etc. I'll do a bit more diagnosing on my end and respond back once I know more.

There does need to be some stricter rate limiting on failed auth requests I think generally speaking.

**Comment by drhex2000** [comment]
Same issue here on latest UIP 4.0.33. Video download is failing most of the time. Gets 5-6 clips from time to time and fails otherwise with 401. This is installed locally without Docker on a WS2022.

**Comment by raluaces** [comment]
Sadly also hitting this on protect 4.1.53, UDMP w/ 4.0.6.

**Comment by ep1cman** [comment]
Exponential backup has been implemented so the next release should address this
