### ISSUE TITLE
rclone remote mount help

### ISSUE THREAD

**Issue by mihcox** [ep1cman/unifi-protect-backup#174]
* Unifi Protect Backup version: unifi-protect-backup:latest
* Unifi Protect version: Protect 5.0.45
* Python version:
* Operating System: UNRAID
* Are you using a docker container or native?: DOCKER

### Description

Trying to add a new remote path, which works over my cmd, but does not work via unraid docker container.

### What I Did

rclone destination: TrueNas:/
Container Variable: RCLONE_DESTINATION
`rclone` destination path in the format {rclone remote}:{path on remote}. E.g.`gdrive:/backups/unifi_protect`

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 189, in start
    await self._check_rclone()
  File "/usr/lib/python3.12/site-packages/unifi_protect_backup/unifi_protect_backup_core.py", line 331, in _check_rclone
    raise ValueError(f"rclone does not have a remote called `{remote}`")
ValueError: rclone does not have a remote called `TrueNas`
v

But when running via the command line to validate the rclone config, it works as expected. Any advice?

rclone copy /mnt/user/Photo/To\ Sort/ 'TrueNas:Content/Camera Recorings'

runs without issue

**Comment by ep1cman** [comment]
This is usually caused by incorrectly mounting the config file into the container. I would suggest getting a console into the container and checking if the file is where you expect it to be with the contents you expect
