### ISSUE TITLE
Rclone: Failed to create file system for (remote) didn't find section in config file

### ISSUE THREAD

**Issue by Shaver443** [ep1cman/unifi-protect-backup#29]
* Unifi Protect Backup version: 0.5.3
* Python version: 3.9+
* Operating System: Docker / Linux

### Description

I am trying to get rclone to backup to Wasabi S3 compatible storage.
Whenever I make the rclone.conf file and setup with the Wasabi info it errors on me.

I'ved tested with another python script and using the cli for rclone that I am able to upload files and data to this bucket.

Super stumped on this on.

### What I Did
here is my rclone.conf file
```
[wasabi]
env_auth = false
access_key_id = redacted
secret_access_key = redacted
region = us-west-1
endpoint = s3.us-west-1.wasabisys.com
location_constraint =
acl = public-read-write
server_side_encryption =
storage_class =
no_check_bucket = true

```

Here is the debug log from Docker
```
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	Config:
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  address='10.0.0.1'
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  port=443
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  username='unifiapi'
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  password=REDACTED
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  verify_ssl=False
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  rclone_destination='wasabi:asher-upb'
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  retention='7d'
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  rclone_args=''
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  ignore_cameras=()
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  verbose=1
2022-03-13 08:40:04 [INFO]:unifi_protect_backup.unifi_protect_backup:	Starting...
2022-03-13 08:40:04 [INFO]:unifi_protect_backup.unifi_protect_backup:	Checking rclone configuration...
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	rclone found: /usr/bin/rclone
2022-03-13 08:40:04 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	ffprobe found: /usr/bin/ffprobe
2022-03-13 08:40:04 [INFO]:unifi_protect_backup.unifi_protect_backup:	Connecting to Unifi Protect...
2022-03-13 08:40:05 [INFO]:unifi_protect_backup.unifi_protect_backup:	Found cameras:
2022-03-13 08:40:05 [INFO]:unifi_protect_backup.unifi_protect_backup:	 - 608465ec02d04b0387004231: Front Door
2022-03-13 08:40:05 [INFO]:unifi_protect_backup.unifi_protect_backup:	 - 6227ff2001adcd0387001ab4: Side Patio
2022-03-13 08:40:05 [INFO]:unifi_protect_backup.unifi_protect_backup:	Setting up purge task...
2022-03-13 08:40:05 [INFO]:unifi_protect_backup.unifi_protect_backup:	Listening for events...
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	Adding event 622dadf803b207038700144f to queue (Current queue=1)
2022-03-13 08:40:38 [INFO]:unifi_protect_backup.unifi_protect_backup:	Backing up event: 622dadf803b207038700144f
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	Remaining Queue: 0
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Camera: Front Door
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Type: motion
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Start: 2022-03-13T08-40-21 (1647160821.808)
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  End: 2022-03-13T08-40-37 (1647160837.471)
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Duration: 15.663
2022-03-13 08:40:38 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Sleeping (6.052519s) to ensure clip is ready to download...
2022-03-13 08:40:44 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Downloading video...
2022-03-13 08:40:45 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Downloaded video length: 16.201s(+0.538s)
2022-03-13 08:40:45 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	  Uploading video via rclone...
2022-03-13 08:40:45 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	    To: wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4
2022-03-13 08:40:45 [DEBUG]:unifi_protect_backup.unifi_protect_backup:	    Size: 3.7MiB
2022-03-13 08:40:45 [WARNING]:unifi_protect_backup.unifi_protect_backup:	    Failed upload attempt 1, retying in 1s
2022-03-13 08:40:45 [ERROR]:unifi_protect_backup.unifi_protect_backup:	Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:45 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:45 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:45 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:45 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:45 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 504, in _backup_events
    await self._upload_video(video, destination, self.rclone_args)
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 546, in _upload_video
    raise SubprocessException(stdout.decode(), stderr.decode(), proc.returncode)
unifi_protect_backup.unifi_protect_backup.SubprocessException: Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:45 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:45 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:45 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:45 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:45 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
2022-03-13 08:40:46 [ERROR]:asyncio             :	Future exception was never retrieved
future: <Future finished exception=BrokenPipeError()>
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/subprocess.py", line 153, in _feed_stdin
    await self.stdin.drain()
  File "/usr/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/lib/python3.9/asyncio/streams.py", line 197, in _drain_helper
    await waiter
BrokenPipeError
2022-03-13 08:40:46 [WARNING]:unifi_protect_backup.unifi_protect_backup:	    Failed upload attempt 2, retying in 1s
2022-03-13 08:40:46 [ERROR]:unifi_protect_backup.unifi_protect_backup:	Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:46 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:46 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:46 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:46 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:46 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 504, in _backup_events
    await self._upload_video(video, destination, self.rclone_args)
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 546, in _upload_video
    raise SubprocessException(stdout.decode(), stderr.decode(), proc.returncode)
unifi_protect_backup.unifi_protect_backup.SubprocessException: Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:46 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:46 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:46 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:46 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:46 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
2022-03-13 08:40:47 [WARNING]:unifi_protect_backup.unifi_protect_backup:	    Failed upload attempt 3, retying in 1s
2022-03-13 08:40:47 [ERROR]:unifi_protect_backup.unifi_protect_backup:	Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:47 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:47 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:47 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:47 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:47 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 504, in _backup_events
    await self._upload_video(video, destination, self.rclone_args)
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 546, in _upload_video
    raise SubprocessException(stdout.decode(), stderr.decode(), proc.returncode)
unifi_protect_backup.unifi_protect_backup.SubprocessException: Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:47 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:47 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:47 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:47 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:47 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
2022-03-13 08:40:48 [WARNING]:unifi_protect_backup.unifi_protect_backup:	    Failed upload attempt 4, retying in 1s
2022-03-13 08:40:48 [ERROR]:unifi_protect_backup.unifi_protect_backup:	Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:48 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:48 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:48 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:48 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:48 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 504, in _backup_events
    await self._upload_video(video, destination, self.rclone_args)
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 546, in _upload_video
    raise SubprocessException(stdout.decode(), stderr.decode(), proc.returncode)
unifi_protect_backup.unifi_protect_backup.SubprocessException: Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:48 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:48 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:48 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:48 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:48 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
2022-03-13 08:40:49 [WARNING]:unifi_protect_backup.unifi_protect_backup:	    Failed upload attempt 5, retying in 1s
2022-03-13 08:40:49 [ERROR]:unifi_protect_backup.unifi_protect_backup:	Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:49 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:49 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:49 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:49 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:49 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 504, in _backup_events
    await self._upload_video(video, destination, self.rclone_args)
  File "/usr/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 546, in _upload_video
    raise SubprocessException(stdout.decode(), stderr.decode(), proc.returncode)
unifi_protect_backup.unifi_protect_backup.SubprocessException: Return Code: 1
Stdout:
Stderr:
2022/03/13 08:40:49 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"
2022/03/13 08:40:49 DEBUG : rclone: Version "v1.57.0-DEV" starting with parameters ["rclone" "rcat" "-vv" "wasabi:asher-upb/Front Door/2022-03-13/2022-03-13T08-40-21 motion.mp4"]
2022/03/13 08:40:49 DEBUG : Creating backend with remote "wasabi:asher-upb/Front Door/2022-03-13/"
2022/03/13 08:40:49 DEBUG : Using config file from "/config/rclone/rclone.conf"
2022/03/13 08:40:49 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
2022-03-13 08:40:50 [WARNING]:unifi_protect_backup.unifi_protect_backup:	Upload failed after 5 attempts, abandoning event 622dadf803b207038700144f:
```

**Comment by ep1cman** [comment]
Can you share your rclone conf file, obviously redacting any passwords/keys. Given the following error:
```
 Failed to create file system for "wasabi:asher-upb/Front Door/2022-03-13/": didn't find section in config file
 ```
 I suspect the issue is with the remote name `wasabi`

**Comment by ep1cman** [comment]
Try adding a '/' after the ':' e.g `wasabi:/asher-upb`. Are you running this in a container? If so its also work checking if the config file is actually being picked up inside the container

**Comment by Shaver443** [comment]
Went ahead and put in the '/' in my remote name. I was looking in the volume under '_data/rclone/' the rclone.conf file was in there. I ended up making a new directory and moving the config file there and then mapped it to /config in the container. It's all working now.
Thanks for the quick reply! I was totally stumped last night. Couldn't figure our if it was a Wasabi issue or an Rclone issue. It appears it was me lol.
