### ISSUE TITLE
New Unifi protect version appears to have broken backup

### ISSUE THREAD

**Issue by timotab** [ep1cman/unifi-protect-backup#39]
* Unifi Protect Backup version: 0.7.0
* Python version: 3.9.10
* Operating System: Rasbian 10

### Description

Had been running the backups fine. Updated Unifi protect to 2.0.1, backups started failing. Log from unifi protect showing successful downloads, then protect update, then no more successful downloads in attached screenshot
<img width="1476" alt="Screen Shot 2022-06-07 at 12 37 46 PM" src="https://user-images.githubusercontent.com/2607526/172447794-c7c313f8-27b6-4318-88dd-afcd3532e5de.png">

### What I Did

```
unifi-protect-backup --address 192.168.1.1 --no-verify-ssl --rclone-destination awsbackups:${BUCKTPREFIX}

2022-06-07 12:39:59 [INFO]:unifi_protect_backup.unifi_protect_backup:	Starting...
2022-06-07 12:39:59 [INFO]:unifi_protect_backup.unifi_protect_backup:	Checking rclone configuration...
2022-06-07 12:39:59 [INFO]:unifi_protect_backup.unifi_protect_backup:	Connecting to Unifi Protect...
Traceback (most recent call last):
  File "/home/thunt/unifi-backup/bin/unifi-protect-backup", line 8, in <module>
    sys.exit(main())
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/unifi_protect_backup/cli.py", line 109, in main
    loop.run_until_complete(event_listener.start())
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 288, in start
    await self._protect.update()
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/api.py", line 507, in update
    self._bootstrap = await self.get_bootstrap()
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/api.py", line 676, in get_bootstrap
    return Bootstrap.from_unifi_dict(**data, api=self)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 106, in from_unifi_dict
    data = cls.unifi_dict_to_dict(data)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/bootstrap.py", line 152, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 338, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj_dict(data[key], unifi_dicts[key], api)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 283, in _clean_protect_obj_dict
    items[key] = cls._clean_protect_obj(value, klass, api)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 267, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/devices.py", line 698, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 612, in unifi_dict_to_dict
    return super().unifi_dict_to_dict(data)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 328, in unifi_dict_to_dict
    data[key] = cls._clean_protect_obj(data[key], unifi_objs[key], api)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 267, in _clean_protect_obj
    return klass.unifi_dict_to_dict(data=data)
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/data/base.py", line 321, in unifi_dict_to_dict
    data[key] = convert_unifi_data(data[key], cls.__fields__[key])
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 160, in convert_unifi_data
    value = [convert_unifi_data(v, field) for v in value]
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 160, in <listcomp>
    value = [convert_unifi_data(v, field) for v in value]
  File "/home/thunt/unifi-backup/lib/python3.9/site-packages/pyunifiprotect/utils.py", line 176, in convert_unifi_data
    value = field.type_(value)
  File "/usr/local/lib/python3.9/enum.py", line 384, in __call__
    return cls.__new__(cls, value)
  File "/usr/local/lib/python3.9/enum.py", line 702, in __new__
    raise ve_exc
ValueError: 'package' is not a valid SmartDetectObjectType
2022-06-07 12:40:01 [ERROR]:asyncio             :	Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0xb4ecebb0>
2022-06-07 12:40:01 [ERROR]:asyncio             :	Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0xb4ee9538>, 1580.794824017)]']
connector: <aiohttp.connector.TCPConnector object at 0xb4ecedf0>

```

**Comment by ep1cman** [comment]
Thanks for reporting this. I was using it with the 2.0.0 for a while without a problem and other users have commented that it works fine. Having said that, this very much is an issue. I wonder how come you're the first to have issues.

I will try investigate and get a solution soon but I just moved house and my unifi setup is not fully setup at the moment so please bare with me.

**Comment by timotab** [comment]
FWIW, I updated to 2.0.0 on May 26, and that was working fine - it's definitely 2.0.1 that coincided with the issue.

**Comment by ep1cman** [comment]
Ah very interesting, thanks for letting me know!

**Comment by ep1cman** [comment]
I just bumped to the latest version of the pyunifiprotect libary that this tool relies on heavily and it seems to be working ok on my 2.0.1 setup (with the two motion events I created in my network cupboard). Can you please test out the `dev` branch and see if it makes any difference? (If you are using the docker container please use the `:dev` tag)

**Comment by ep1cman** [comment]
It seems they have also changed the way user accounts are created and they need to be "assigned" cameras. Please check the readme on `dev` for instructions.

**Comment by timotab** [comment]
I'm not able to follow the instructions you've got here to assign cameras. Not finding the tabs/sections you describe.

**Comment by ep1cman** [comment]
<img width="1440" alt="Screenshot 2022-06-08 at 00 04 55" src="https://user-images.githubusercontent.com/5303409/172497466-99309092-e2e7-4df6-8f51-c241be569b03.png">

**Comment by timotab** [comment]
I get "Overview" and "Profile" tabs on the right sidebar; no "Assignment" or "Settings" tabs. 
<img width="386" alt="Screen Shot 2022-06-07 at 7 11 44 PM" src="https://user-images.githubusercontent.com/2607526/172504682-deea88c6-374a-44f5-b02d-67110e18a36a.png">

**Comment by timotab** [comment]
Huh, just noticed that the console itself was on 1.11.4 - now updating to 1.12.22 to see if that changes things.

**Comment by ep1cman** [comment]
I think it could be because the "Limited Admin" role already has high enough priviledges that it does bother showing some things like assignments of cameras

**Comment by timotab** [comment]
Looks like the camera assignment is new in the main unifi console app, which is now updated. 

Then I finally updated the pyunifiprotect library to 3.9.0 and that seems to have fixed it. No longer crashes, and video is uploading to S3

**Comment by ep1cman** [comment]
Thanks for confirming. I have now pushed a new release with the changes made to resolve this

**Comment by roastlechon** [comment]
> 

Haha! I was looking through here to see if anyone had any issues and was thinking it was on my end so I never reported!

Thanks for  fixing!
