### ISSUE TITLE
New version not recognizing destination

### ISSUE THREAD

**Issue by ouaibe** [ep1cman/unifi-protect-backup#60]
* Unifi Protect Backup version:
0.8.1
* Unifi Protect version:
2.2.6
* Python version:
3.10.8
* Operating System:
https://hub.docker.com/r/truecharts/unifi-protect-backup/tags

* Are you using a docker container or native?:
Docker container

### Description

My configuration was running fine until the latest update.

The current setup is for a B2 remote with an encrypted overlay.

The config that unifi-protect-backup runs under points to the CRYPT_NAME destination (the encrypted overlay), with a trailing `:` since it doesn't need a path (being a overlay encryption to the other real remote destination, that is).

**Somehow it seems the trailing colon gets removed at some point causing the script to crash?**

This is the Rclone config:

```
[NAME]
type = b2
account = <REDACTED>
key = <REDACTED>
download_auth_duration = 1m0s

[CRYPT_NAME]
type = crypt
remote = NAME:/PATH
directory_name_encryption = <REDACTED>
password = <REDACTED>
filename_encryption = <REDACTED>
```

The Docker variables are thus set accordingly.

```
root@truecharts-unifi-protect-backup1:/app# echo $RCLONE_DESTINATION                                                                                                                         
CRYPT_NAME:                                                                                                                                                                             
root@truecharts-unifi-protect-backup1:/app# rclone --config /config/rclone/rclone.conf listremotes                                                                                           
NAME:                                                                                                                                                                                   
CRYPT_NAME:
```` 

### What I Did

Confirmed that by simply rolling back to the previous Docker image (based on August's v 0.7.4 release) it works fine with the exact same setup.

Actual error message (names replaced accordingly):

```

-------------------------------------

[custom-init] No custom files found, skipping...

services-up: info: copying legacy longrun unifi-protect-backup (no readiness notification)

[ls.io-init] done.

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	Config:

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  address='<REDACTED>'

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  port=<REDACTED>

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  username='<REDACTED>'

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  password=REDACTED

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  verify_ssl=False

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  rclone_destination='CRYPT_NAME:'

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  retention='60d'

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  rclone_args=''

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  ignore_cameras=()

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  verbose=4

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  detection_types=['motion', 'person', 'vehicle', 'ring']

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  file_structure_format='{camera_name}/{event.start:%Y-%m-%d}/{event.end:%Y-%m-%dT%H-%M-%S} {detection_type}.mp4'

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	  sqlite_path='/config/database/events.sqlite'

2022-12-05 12:13:58 [   INFO    ] unifi_protect_backup.unifi_protect_backup  :	Starting...

2022-12-05 12:13:58 [   INFO    ] unifi_protect_backup.unifi_protect_backup  :	Checking rclone configuration...

2022-12-05 12:13:58 [   DEBUG   ] unifi_protect_backup.unifi_protect_backup  :	rclone found: /usr/bin/rclone

2022-12-05 12:13:58 [EXTRA_DEBUG] unifi_protect_backup.utils                 :	stdout:

NAME:

	CRYPT_NAME:

2022-12-05 12:13:58 [EXTRA_DEBUG] unifi_protect_backup.utils                 :	stderr:

2022/12/05 12:13:58 DEBUG : Setting --config "/config/rclone/rclone.conf" from environment variable RCLONE_CONFIG="/config/rclone/rclone.conf"

	2022/12/05 12:13:58 DEBUG : rclone: Version "v1.58.1-DEV" starting with parameters ["rclone" "listremotes" "-vv"]

	2022/12/05 12:13:58 DEBUG : Using config file from "/config/rclone/rclone.conf"

	2022/12/05 12:13:58 DEBUG : rclone: Version "v1.58.1-DEV" finishing with parameters ["rclone" "listremotes" "-vv"]

2022-12-05 12:13:58 [   ERROR   ] asyncio                                    :	Task exception was never retrieved

future: <Task finished name='Task-1' coro=<run.<locals>.new_coro() done, defined at /usr/lib/python3.10/site-packages/aiorun.py:227> exception=ValueError('rclone does not have a remote called `CRYPT_NAME`')>

Traceback (most recent call last):

  File "/usr/lib/python3.10/site-packages/aiorun.py", line 237, in new_coro

    await coro

  File "/usr/lib/python3.10/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 281, in start

    await self._check_rclone()

  File "/usr/lib/python3.10/site-packages/unifi_protect_backup/unifi_protect_backup.py", line 373, in _check_rclone

    raise ValueError(f"rclone does not have a remote called `{remote}`")

ValueError: rclone does not have a remote called `CRYPT_NAME`
```

**Comment by ep1cman** [comment]
I've been able to reporduce this locally, will get a fix out ASAP

**Comment by ep1cman** [comment]
The issue has been fixed, a new build should be available in ~30mins

The cause was me adding indentation to stdout/stderr of the sub commands executed to make the logs easier to read, but this was also being passed on to the rest of the code which then failed to parse the output correctly

**Comment by ouaibe** [comment]
Thanks for the quick reaction and explanation, as soon as a build is out/released and I can get my hands on an updated Docker image, I will report here.

**Comment by ouaibe** [comment]
I can confirm that the fix worked for the previous error, although the creation of the `/database` directory wasn't done automatically for some reason, after a manual creation all seem well.
