### ISSUE TITLE
'NoneType' object has no attribute 'id'

### ISSUE THREAD

**Issue by Swallowtail23** [ep1cman/unifi-protect-backup#64]
* Unifi Protect Backup version: 0.8.5
* Unifi Protect version:
* Python version:
* Operating System:
* Are you using a docker container or native?: Container

### Description

Error message per below

### What I Did

Started the container...

```
2022-12-10 00:17:06 [   INFO    ] unifi_protect_backup.missing_event_checker :  Starting Missing Event Checker
2022-12-10 00:17:11 [  WARNING  ] unifi_protect_backup.missing_event_checker :  Unexpected exception occurred during missing event check:
2022-12-10 00:17:11 [   ERROR   ] unifi_protect_backup.missing_event_checker :  'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/unifi_protect_backup/missing_event_checker.py", line 65, in start
    downloading_event_ids.add(self._downloader.current_event.id)
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by jtscott** [comment]
I just updated as well after quite some time. Here is my error

`2022-12-09 17:31:59 [   DEBUG   ] unifi_protect_backup.downloader            :  ffprobe found: /usr/bin/ffprobe
2022-12-09 17:31:59 [   INFO    ] unifi_protect_backup.unifi_protect_backup  :  Starting...
2022-12-09 17:31:59 [   INFO    ] unifi_protect_backup.downloader            :  Starting Downloader
2022-12-09 17:31:59 [   INFO    ] unifi_protect_backup.uploader              :  Starting Uploader
2022-12-09 17:31:59 [   DEBUG   ] unifi_protect_backup.event_listener        :  Subscribed to websocket
2022-12-09 17:31:59 [   INFO    ] unifi_protect_backup.missing_event_checker :  Starting Missing Event Checker
2022-12-09 17:32:01 [  WARNING  ] unifi_protect_backup.missing_event_checker :  Unexpected exception occurred during missing event check:
2022-12-09 17:32:01 [   ERROR   ] unifi_protect_backup.missing_event_checker :  'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/unifi_protect_backup/missing_event_checker.py", line 65, in start
    downloading_event_ids.add(self._downloader.current_event.id)
AttributeError: 'NoneType' object has no attribute 'id'
([\d.]+)(B|KiB|MiB|GiB|TiB|PiB|EiB|ZiB|YiB)
[custom-init] No custom services found, skipping...
[migrations] started
[migrations] no migrations found
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

[custom-init] No custom files found, skipping...
[ls.io-init] done.
v`

**Comment by ep1cman** [comment]
Sorry, I rushed a release last night when I had a spare moment and didn't test properly. 

A fix has just been pushed and being released.

Fun story: since the CI for this repo is setup to
 - build the package and push to PyPI
 - build a x86 and aarch64 container and push it to the container registry 

I was able to fix this from my phone on a train travelling through Cambridgeshire countryside at 6am 😃 We live in the future!

Once again sorry for the issues!

**Comment by jtscott** [comment]
Thank you ❤️

**Comment by Swallowtail23** [comment]
On 0.8.6, a different error. 
```
2022-12-10T23:52:37.646168970+10:00 stderr F 2022-12-10 13:52:37 [   ERROR   ] unifi_protect_backup.missing_event_checker :  'tuple' object has no attribute 'id'
2022-12-10T23:52:37.646168970+10:00 stderr F Traceback (most recent call last):
2022-12-10T23:52:37.646168970+10:00 stderr F   File "/usr/lib/python3.10/site-packages/unifi_protect_backup/missing_event_checker.py", line 69, in start
2022-12-10T23:52:37.646168970+10:00 stderr F     uploading_event_ids = {event.id for event in self._uploader.upload_queue._queue}
2022-12-10T23:52:37.646168970+10:00 stderr F   File "/usr/lib/python3.10/site-packages/unifi_protect_backup/missing_event_checker.py", line 69, in <setcomp>
2022-12-10T23:52:37.646168970+10:00 stderr F     uploading_event_ids = {event.id for event in self._uploader.upload_queue._queue}
2022-12-10T23:52:37.646168970+10:00 stderr F AttributeError: 'tuple' object has no attribute 'id'
2022-12-10T23:52:41.145633913+10:00 stderr F 2022-12-10 13:52:41 [   INFO    ] unifi_protect_backup.uploader              : [63948ed003a1bf03e40efc88]  Uploading event: 63948ed003a1bf03e40efc88
2022-12-10T23:52:56.383474684+10:00 stderr F 2022-12-10 13:52:56 [   INFO    ] 
```

**Comment by ep1cman** [comment]
Sorry been a busy few days for me I will address this tonight and test it properly
________________________________

**Comment by Swallowtail23** [comment]
All good... thank you. I've updated to 0.8.7, will see how it runs. 

Two suggestions:

1. In the container boot, log the version, i.e. this line:
```
2022-12-12T11:37:41.962213664+10:00 stderr F 2022-12-12 01:37:41 [   INFO    ] unifi_protect_backup.unifi_protect_backup  :  Starting...
```
Could be:
```
2022-12-12T11:37:41.962213664+10:00 stderr F 2022-12-12 01:37:41 [   INFO    ] unifi_protect_backup.unifi_protect_backup  :  Starting v0.8.7...
```

2. I have podman (docker) set to use my local timezone, and the logging shows that is working (note above line starts with 2022-12-12T11:37:41.962213664+10:00, i.e. UTC+10), but UPB's logging uses **only** UTC:
```
2022-12-12 01:37:41 [   INFO    ] unifi_protect_backup.unifi_protect_backup  :  Starting...
```
Can UPB use the container's TZ instead of UTC?

**Comment by ep1cman** [comment]
Could you open a new issue to track the timezone bug. I'll add the version string on whatever ends up being the next release.

I'll close this issue now as it sends to be working now
